apiVersion: v1
kind: Secret
metadata:
  name: microservice-secrets
  namespace: default
type: Opaque
# Values are base64-encoded. To encode: echo -n 'yourvalue' | base64
# JWT_SECRET: 'supersecretkey123' -> c3VwZXJzZWNyZXRrZXkxMjM=
data:
  JWT_SECRET: c3VwZXJzZWNyZXRrZXkxMjM=
