name: Build & Push Images

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Build & Push Auth Service
        run: |
          docker build -t $DOCKERHUB_USERNAME/auth-service:${{ github.sha }} ./auth-service
          docker push $DOCKERHUB_USERNAME/auth-service:${{ github.sha }}

      - name: Build & Push Product Service
        run: |
          docker build -t $DOCKERHUB_USERNAME/product-service:${{ github.sha }} ./product-service
          docker push $DOCKERHUB_USERNAME/product-service:${{ github.sha }}

      - name: Build & Push Order Service
        run: |
          docker build -t $DOCKERHUB_USERNAME/order-service:${{ github.sha }} ./order-service
          docker push $DOCKERHUB_USERNAME/order-service:${{ github.sha }}

      - name: Build & Push Frontend
        run: |
          docker build -t $DOCKERHUB_USERNAME/frontend:${{ github.sha }} ./frontend
          docker push $DOCKERHUB_USERNAME/frontend:${{ github.sha }}