name: Build & Push Images

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin

      # AUTH SERVICE
      - name: Build & Push Auth Service
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $DOCKERHUB_USERNAME/auth-service:${{ github.sha }} \
            ./auth-service \
            --push

      # PRODUCT SERVICE
      - name: Build & Push Product Service
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $DOCKERHUB_USERNAME/product-service:${{ github.sha }} \
            ./product-service \
            --push

      # ORDER SERVICE
      - name: Build & Push Order Service
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $DOCKERHUB_USERNAME/order-service:${{ github.sha }} \
            ./order-service \
            --push

      # FRONTEND
      - name: Build & Push Frontend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $DOCKERHUB_USERNAME/frontend:${{ github.sha }} \
            ./frontend \
            --push